version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: smart-portfolio-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: smart-portfolio-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: smart-portfolio-mysql
    ports:
      - "3307:3306"  # Port değiştirildi: 3306 -> 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_portfolio_db
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: portfolio_pass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
  redis_data:
  mysql_data:

